'use client';
import {useEffect,useRef,useState} from 'react';
import {APIProvider,Map,AdvancedMarker} from '@vis.gl/react-google-maps';
import {LocateFixed} from 'lucide-react';
import 'leaflet/dist/leaflet.css';
export default function MapPicker({lat,lng,onChange}:{lat:number;lng:number;onChange:(lat:number,lng:number)=>void}){const ref=useRef<HTMLDivElement>(null);const [error,setError]=useState('');const cb=useRef(onChange);cb.current=onChange;const mapRef=useRef<import('leaflet').Map|null>(null);const marker=useRef<import('leaflet').CircleMarker|null>(null);const key=process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
useEffect(()=>{if(key||!ref.current)return;let disposed=false;import('leaflet').then(L=>{if(disposed||!ref.current)return;const m=L.map(ref.current).setView([lat,lng],14);mapRef.current=m;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(m).on('tileerror',()=>setError('Peta gagal dimuat. Coba koneksi lain atau gunakan lokasi perangkat.'));marker.current=L.circleMarker([lat,lng],{radius:10,color:'#fff',weight:3,fillColor:'#2621df',fillOpacity:1}).addTo(m);m.on('click',e=>cb.current(e.latlng.lat,e.latlng.lng));});return()=>{disposed=true;mapRef.current?.remove();mapRef.current=null;};},[key]);
useEffect(()=>{marker.current?.setLatLng([lat,lng]);mapRef.current?.panTo([lat,lng]);},[lat,lng]);
return <div className="map-wrap">{key?<APIProvider apiKey={key}><Map defaultCenter={{lat,lng}} defaultZoom={14} mapId="DEMO_MAP_ID" onClick={e=>{if(e.detail.latLng)onChange(e.detail.latLng.lat,e.detail.latLng.lng)}}><AdvancedMarker position={{lat,lng}} draggable onDragEnd={e=>{if(e.latLng)onChange(e.latLng.lat(),e.latLng.lng())}}/></Map></APIProvider>:<div className="map" ref={ref}/>}<button type="button" className="locate" onClick={()=>{if(!navigator.geolocation){setError('Lokasi perangkat tidak tersedia');return;}navigator.geolocation.getCurrentPosition(p=>{onChange(p.coords.latitude,p.coords.longitude);setError('');},()=>setError('Izin lokasi ditolak. Ketuk titik pada peta untuk memilih.'));}}><LocateFixed size={15}/> Lokasi saya</button><small>{error||`Ketuk peta untuk menentukan titik jemput · ${lat.toFixed(5)}, ${lng.toFixed(5)}`}</small></div>}
